version: '2'
services:
    microserviceapplication-app:
        image: microserviceapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://microserviceapplication-mysql:3306/microserviceapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=microserviceapplication-elasticsearch:9300
        ports:
            - 8080:8080
    microserviceapplication-mysql:
        extends:
            file: mysql.yml
            service: microserviceapplication-mysql
    microserviceapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: microserviceapplication-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
